# Generated by Django 5.2.16 on 2026-07-18 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cliente_id', models.UUIDField(help_text="Riferimento al cliente nell'anagrafica condivisa del Portale.")),
                ('sito', models.CharField(blank=True, help_text='Es. "SHOP Prada Vienna Ground Floor": può essere diverso dal cliente in anagrafica.', max_length=255, verbose_name='Sito / cliente finale')),
                ('data_intervento', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creato_il'],
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('progetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_set', to='cablaggio.progetto')),
            ],
            options={
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ElementoRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('patch_panel', 'Patch panel'), ('cassetto_fibra', 'Cassetto fibra')], max_length=20)),
                ('etichetta', models.CharField(help_text='Es. "A", "B", "C".', max_length=10, verbose_name='Etichetta')),
                ('n_posizioni', models.PositiveSmallIntegerField(choices=[(8, '8 posizioni'), (12, '12 posizioni'), (16, '16 posizioni'), (24, '24 posizioni')], verbose_name='Posizioni')),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementi', to='cablaggio.rack')),
            ],
            options={
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RackAllegato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='rackreport_allegati/%Y/%m/')),
                ('nome_originale', models.CharField(blank=True, max_length=255)),
                ('caricato_il', models.DateTimeField(auto_now_add=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allegati', to='cablaggio.rack')),
            ],
            options={
                'ordering': ['-caricato_il'],
            },
        ),
        migrations.CreateModel(
            name='Posizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text="Numero della posizione all'interno del pannello (1..N).")),
                ('cavo_n', models.CharField(blank=True, max_length=50, verbose_name='N° cavo')),
                ('tipo_cavo', models.CharField(blank=True, max_length=100, verbose_name='Tipo cavo')),
                ('descrizione', models.CharField(blank=True, max_length=255)),
                ('posizione_in_campo', models.CharField(blank=True, max_length=100)),
                ('esito_test', models.CharField(blank=True, choices=[('', '— non testato —'), ('ok', 'OK'), ('p2', 'P2')], max_length=2)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posizioni', to='cablaggio.elementorack')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('elemento', 'numero')},
            },
        ),
    ]
