# Generated by Django 5.2.16 on 2026-07-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cablaggio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='posizione',
            field=models.CharField(blank=True, help_text='Dove si trova fisicamente il rack, es. "Sala CED, piano terra".', max_length=255),
        ),
    ]
