# Generated by Django 5.2.16 on 2026-07-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cablaggio', '0002_rack_posizione'),
    ]

    operations = [
        migrations.AddField(
            model_name='posizione',
            name='porta_label',
            field=models.CharField(blank=True, help_text='Sovrascrive il numero di porta calcolato automaticamente. Usato per i cassetti fibra, dove la numerazione fisica delle porte spesso non è progressiva come nei patch panel.', max_length=20, verbose_name='Porta'),
        ),
    ]
