# Generated by Django 5.2.16 on 2026-07-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cablaggio', '0003_posizione_porta_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='progetto',
            name='logo_cliente',
            field=models.ImageField(blank=True, help_text='Mostrato in testa alla scheda progetto e nella prima pagina del report PDF.', null=True, upload_to='loghi_cliente/%Y/%m/', verbose_name='Logo cliente'),
        ),
    ]
