# Generated by Django 5.2.16 on 2026-08-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cablaggio', '0007_rimuovi_vecchi_campi_tipo_cavo_esito_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='progetto',
            name='lingue_report',
            field=models.CharField(default='it', help_text='Lingue in cui generare il report PDF: se ne scegli più di una, il report le contiene tutte in sequenza.', max_length=20, verbose_name='Lingue report PDF'),
        ),
    ]
