# Generated by Django 5.2.16 on 2026-08-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cablaggio', '0008_progetto_lingue_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progetto',
            name='lingue_report',
        ),
    ]
